### PR TITLE
Show RAM warning in GUI / log in CLI

### PR DESCRIPTION
**Pull request by ziw-liu**
The RAM implementation in [#157](https://github.com/mehta-lab/recOrder/pull/157#discussion_r972256905) does not offer a visual hint in the GUI. The use of `print()` in the CLI also limited the way we can format the message. Here is a modified version with a more portable API.

### CODE REVIEW

**Comment by talonchandler** [comment]
Look good...I'm on board. 

Would you mind testing this before merging? I think it will be easiest to test locally or on the HPC where you can control how much RAM is available.

**Comment by ziw-liu** [comment]
> Would you mind testing this before merging? I think it will be easiest to test locally or on the HPC where you can control how much RAM is available.
I tested locally (16 GB RAM) and on the Automaton computer (128 GB RAM) and it works as expected.
Not sure about the CLI part yet.

**Comment by ziw-liu** [comment]
@talonchandler can you help test on the CLI to see if the message is displayed properly?

**Comment by talonchandler** [comment]
@ziw-liu When you tested the napari `showwarning` function, did your warning messages persist in napari? 

I'm finding that as I step through `showwarning` I get the correct warning message, but when I run it normally the message doesn't persist.

**Comment by ziw-liu** [comment]
> did your warning messages persist in napari?

I think napari manages the persistence of the message. In my testing it'll only stay on for a few seconds but will persist if you click the expand icon.

**Comment by talonchandler** [comment]
I just tested the CLI and the message appears as expected. 

I also changed the behavior so that the message appears in napari when you run the pipeline in offline mode.

**Review by talonchandler — APPROVED** [review]

**Comment by ziw-liu** [comment]
> I also changed the behavior so that the message appears in napari when you run the pipeline in offline mode.
Will the method ever be called when there is not a napari instance (e.g. in CLI mode)? That will cause an error.

**Comment by talonchandler** [comment]
Have you tested? I thought it would error, too, but I tried it and I didn't get an error.

**Comment by talonchandler** [comment]
If you haven't run the CLI or offline mode yet, I can give you a quick intro/tutorial. It can be a bit finicky, but it works pretty well.

**Comment by ziw-liu** [comment]
> Have you tested?
No I haven't, just speculating 🤔

**Pull request merged**
