### PR TITLE
Turn live mode off when loading calibration

### LINKED ISSUE #280: "Load calibration" when MM is live gives an error
Clicking "Load calibration" when MM is live errors and gives the attached traceback:

[traceback.txt](https://github.com/mehta-lab/recOrder/files/10026782/traceback.txt)

Easy to work around by turning off "Live Mode". 

Related to #203 and #205.

### PR DESCRIPTION
**Pull request by talonchandler**
Fixes #280 

Tested on hummingbird

### CODE REVIEW

**Comment by ziw-liu** [comment]
To my eyes this is very similar to #282 but glad this worked! @talonchandler maybe also consider using that context manager?

**Comment by talonchandler** [comment]
It looks like we're using the context manager when we capture a background, and we're using these lines for running a calibration (where I got this from) and now for loading a calibration:
```
if self.calib.snap_manager.getIsLiveModeOn():
    self.calib.snap_manager.setLiveModeOn(False)
```

I agree that the context manager should do the same thing, so I don't understand why #282 isn't working. 

Do you think it's worth the effort to test and understand this? Or do you think we should merge this fix and handle later?

**Comment by ziw-liu** [comment]
It seems like #282 didn't work because [the `load_calibration` worker](https://github.com/mehta-lab/recOrder/blob/fbbd7c8b44ea0bdd7b7cb159c390277c2983fd1e/recOrder/calib/calibration_workers.py#L439) makes MMCore calls directly instead of reusing existing methods of the `Calibration` object. I can fix that.

**Review by ziw-liu — APPROVED** [review]
@talonchandler I'm fine with this PR either way since its just a few lines. It's your call whether we need this quick patch for the 0.3 release, but if you decide to merge maybe comment with `FIXME` in the code so that we don't forget about it.

**Comment by talonchandler** [comment]
Thanks for your flexibility @ziw-liu. I've added FIXME comments, and I'm looking forward to moving the MM calls off of the main thread later.

**Pull request merged**
