### PR TITLE
Remove fluorescence, preprocessing, and postprocessing; simplify GUI

### PR DESCRIPTION
**Pull request by talonchandler**
This PR implements several simplifications suggested by @mattersoflight:

- remove all fluorescence features from `recOrder` 
- remove all preprocessing (denoising) and postprocessing (denoising, registration, fluorescence deconvolution) from `recOrder`
- simplify the GUI to reflect these updates: only two tabs of parameters instead of six. 

The removal of fluorescence, preprocessing, and postprocessing features is "deep"---I removed these features from the GUI, the CLI, and the docs (except the overview figure...I'm waiting on an Affinity Designer license). 

@ziw-liu I'm expecting a fair amount of work to test this branch before we're ready to merge. I'd really appreciate your help. 

Thanks!

### CODE REVIEW

**Comment by talonchandler** [comment]
I did a first round of testing on hummingbird and fixed several shallow bugs, so I'll move this from draft to full PR now.

**Comment by ziw-liu** [comment]
The `preproc` and `postproc` submodules contain functionalities that might be reused for 1.0.0, for example those generating overlay visualizations for polarization data. Is it necessary to remove them from `main` for 0.2.0?

**Comment by ziw-liu** [comment]
What is the intention of having 'Acquisition/Reconstruction -> Acquisition Settings -> Acq Channel (BF Only)' in lieu of 'Acq Channel (BF/Fluor Only)? Do we expect to see different BF channels?

**Comment by talonchandler** [comment]
Re: overlay stuff---I moved it all to `utils.py` for now since I didn't think it belonged in postproc. All the other stuff was unneeded imo...and we can pull it up again if it's needed. 

Re multiple BF channels---I think it's unlikely that we'll have multiple BF channels, but there's often some ambiguity in which configuration group/preset correspond to BF, so this setting is still useful.

**Comment by talonchandler** [comment]
> will we need denoising for Stoke's in the future?

Possibly...but I doubt it. I think this is likely more of a `waveorder` script type feature. It's easy to resurrect if we do want it back in recOrder.

**Review by ziw-liu — APPROVED** [review]
I did a quick browse through code changes and some clicking-around on Automaton. No bugs spotted yet.
Tremendous (5×10³-1-1182) lines weight loss! 🏋️

**Pull request merged**
