### PR TITLE
Move docs from wiki to `/docs/`

### PR DESCRIPTION
**Pull request by talonchandler**
This PR:
- moves all docs from the wiki to the `/docs/` folder
- leaves a short set of "Quick Start" installation instructions on the main README, and moves the more detailed developer installation instructions to `/docs/software-installation-guide.md`
- creates a new `/docs/README.md` landing page that directs a new user through the docs depending on their use case. This page includes links to open an issue or send an email if an error in the docs or code is spotted.
- Simplifies the initial README.md: simpler language, no longer referring to a "QLIPP module" which is not defined in the figure or elsewhere. 

I will hide the wiki when this PR merges.

### CODE REVIEW

**Comment by talonchandler** [comment]
This is ready for review @ieivanov. Thanks!

**Comment by ieivanov** [comment]
I like it! I haven't read all the details, but I think it's good to merge

**Review by ieivanov — APPROVED** [review]

**Review by mattersoflight — APPROVED** [review]
These changes look good - I resolved one pending conflict. Merging now.

**Comment by talonchandler** [comment]
Thanks Shalin.  Can you also disable the wiki (`Settings > Features > unselect Wiki` will hide but won't delete)? I don't think I have permission. 
https://docs.github.com/en/communities/documenting-your-project-with-wikis/disabling-wikis

AFAIK Yuming is the only person I've pointed to the wiki, so I will notify him of this move.

**Comment by mattersoflight** [comment]
Thanks @talonchandler. I disabled the wiki and added you again as a maintainer on the repo. I am not sure what happened with permissions.

**Comment by talonchandler** [comment]
Thanks! Now I can access `Settings` etc, so we should be good to go.

**Pull request merged**
