### PR TITLE
QLIPP Pipeline 2D write fix

### PR DESCRIPTION
**Pull request by camFoltz**
Fixed writing bug in 2D stokes, switched to this writing method for the birefringence channel as well.

### CODE REVIEW

**Comment by camFoltz** [comment]
Dont merge until after the workshop

**Comment by bryantChhun** [comment]
Looks fine to me.  You can merge when you feel fit

**Comment by camFoltz** [comment]
Ah i forgot about this, I think that the newest PR has these changes + more

**Comment by camFoltz** [comment]
I will close this PR

**Pull request closed without merging**
