### PR TITLE
Fix 0.4.0dev tests

### PR DESCRIPTION
**Pull request by talonchandler**
This PR against `0.4.0dev` includes the test fixes that should have appeared in #381 (see #383 for CI/CD fix).

### CODE REVIEW

**Comment by talonchandler** [comment]
@ziw-liu I'm having trouble getting the tests on windows. Any idea how we might solve this?

```
>           assert tf_path.exists()
  E           AssertionError: assert False
  E            +  where False = <bound method Path.exists of WindowsPath('C:/Users/runneradmin/AppData/Local/Temp/pytest-of-unknown/pytest-0/test_reconstruct0/tf.zarr')>()
  E            +    where <bound method Path.exists of WindowsPath('C:/Users/runneradmin/AppData/Local/Temp/pytest-of-unknown/pytest-0/test_reconstruct0/tf.zarr')> = WindowsPath('C:/Users/runneradmin/AppData/Local/Temp/pytest-of-unknown/pytest-0/test_reconstruct0/tf.zarr').exists
```

**Comment by ziw-liu** [comment]
I can reproduce the same error on a local Windows machine (automaton 2).

**Comment by ziw-liu** [comment]
OK found it. Same issue as https://github.com/czbiohub-sf/iohub/pull/116/

**Comment by ziw-liu** [comment]
@talonchandler Some new warnings related to torch in addition to the overlay colormap things:

```text
=============================== warnings summary ===============================
  recOrder/tests/cli_tests/test_compute_tf.py::test_compute_transfer
    /home/runner/work/recOrder/recOrder/.tox/py311-linux/lib/python3.11/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
      return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  
  recOrder/tests/cli_tests/test_compute_tf.py::test_compute_transfer
  recOrder/tests/cli_tests/test_compute_tf.py::test_compute_transfer_output_file
  recOrder/tests/cli_tests/test_compute_tf.py::test_absorption_and_phase_write
  recOrder/tests/cli_tests/test_compute_tf.py::test_phase_3dim_write
  recOrder/tests/cli_tests/test_compute_tf.py::test_fluorescence_write
  recOrder/tests/cli_tests/test_reconstruct.py::test_reconstruct
    /home/runner/work/recOrder/recOrder/.tox/py311-linux/lib/python3.11/site-packages/waveorder/optics.py:321: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
      * torch.tensor(z_position_list)[:, None, None]
  
  recOrder/tests/cli_tests/test_compute_tf.py::test_compute_transfer
  recOrder/tests/cli_tests/test_compute_tf.py::test_compute_transfer_output_file
  recOrder/tests/cli_tests/test_compute_tf.py::test_absorption_and_phase_write
  recOrder/tests/cli_tests/test_reconstruct.py::test_reconstruct
    /home/runner/work/recOrder/recOrder/.tox/py311-linux/lib/python3.11/site-packages/waveorder/optics.py:370: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
      * torch.tensor(z_position_list)[:, None, None]
  
  recOrder/tests/cli_tests/test_reconstruct.py::test_reconstruct
    /home/runner/work/recOrder/recOrder/.tox/py311-linux/lib/python3.11/site-packages/waveorder/stokes.py:2[91](https://github.com/mehta-lab/recOrder/actions/runs/5660655330/job/15336852512#step:7:92): UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
      transmittance = torch.tensor(s0).clone()
  
  recOrder/tests/cli_tests/test_reconstruct.py::test_reconstruct
    /home/runner/work/recOrder/recOrder/.tox/py311-linux/lib/python3.11/site-packages/waveorder/util.py:711: RuntimeWarning: invalid value encountered in divide
      img_norm_stack[i] = img_stack[i] / uniform_filter(
  
  recOrder/tests/util_tests/test_overlays.py::test_ret_ori_overlay
  recOrder/tests/util_tests/test_overlays.py::test_ret_ori_overlay
  recOrder/tests/util_tests/test_overlays.py::test_ret_ori_overlay
  recOrder/tests/util_tests/test_overlays.py::test_ret_ori_overlay
    /home/runner/work/recOrder/recOrder/.tox/py311-linux/lib/python3.11/site-packages/recOrder/io/utils.py:271: RuntimeWarning: overflow encountered in divide
      ret_ / np.max(ret_),
  
  recOrder/tests/util_tests/test_overlays.py: 16 warnings
    /home/runner/work/recOrder/recOrder/.tox/py311-linux/lib/python3.11/site-packages/colorspacious/ciecam02.py:333: RuntimeWarning: invalid value encountered in divide
      t = (C
  
  recOrder/tests/util_tests/test_overlays.py::test_ret_ori_overlay
  recOrder/tests/util_tests/test_overlays.py::test_ret_ori_overlay
  recOrder/tests/util_tests/test_overlays.py::test_ret_ori_overlay
    /home/runner/work/recOrder/recOrder/.tox/py311-linux/lib/python3.11/site-packages/colorspacious/ciecam02.py:3[97](https://github.com/mehta-lab/recOrder/actions/runs/5660655330/job/15336852512#step:7:98): RuntimeWarning: invalid value encountered in power
      * ((27.13 * np.abs(RGBprime_a - 0.1))
  
  -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
  
  ---------- coverage: platform linux, python 3.11.4-final-0 -----------
  Coverage XML written to file coverage.xml
  
  ======================= 29 passed, 36 warnings in 11.07s =======================
```

**Comment by talonchandler** [comment]
Thanks @ziw-liu! 

Let me work through these warnings then I'll merge this.

**Comment by talonchandler** [comment]
I've documented the warnings into issues in the correct repositories:

`waveorder`
- [#137](https://github.com/mehta-lab/waveorder/issues/137) - meshgrid warning with [fix PR](https://github.com/mehta-lab/waveorder/pull/138)
- [#139](https://github.com/mehta-lab/waveorder/issues/139) - warning about copying tensors (slightly more involved to fix)
 - [#140](https://github.com/mehta-lab/waveorder/issues/140) - phase normalization divide by zero
 
`recOrder`
- #386 - overlay warnings

None of these warnings are critical, so I vote to merge this branch into `0.4.0dev` then into `main`.

**Review by ziw-liu — APPROVED** [review]

**Pull request merged**
