### PR TITLE
Default HSV colormap

### PR DESCRIPTION
**Pull request by talonchandler**
We typically expect HSV colormaps, so I'm changing the `ret_ori_overlay` function's default.

@edyoshikun related to: https://github.com/czbiohub-sf/shrimPy/pull/141

### CODE REVIEW

**Review by ziw-liu — APPROVED** [review]

**Comment by ziw-liu** [comment]
Now that Qt is fixed, we have a new problem that PyTorch doesn't have a NumPy 2.0 compatible [build on windows](https://github.com/pytorch/pytorch/issues/128860).

**Review by edyoshikun — APPROVED** [review]
LGTM

**Comment by ziw-liu** [comment]
> Now that Qt is fixed, we have a new problem that PyTorch doesn't have a NumPy 2.0 compatible [build on windows](https://github.com/pytorch/pytorch/issues/128860).

Nothing we can do about this one until upstream fixes their CD. Probably just pin numpy<2.0.0 for now.

**Comment by ziw-liu** [comment]
> Nothing we can do about this one until upstream fixes their CD. Probably just pin numpy<2.0.0 for now.

https://github.com/mehta-lab/waveorder/pull/173

**Comment by ziw-liu** [comment]
@talonchandler I think we should merge this since it has the napari fix.

**Pull request merged**
